// JamRadar — sample data

const SPORTS = [
  { id: 'snowboard', label: 'Snowboard', icon: '◣' },
  { id: 'ski',       label: 'Ski',       icon: '◤' },
  { id: 'skate',     label: 'Skate',     icon: '◇' },
  { id: 'mtb',       label: 'MTB',       icon: '◯' },
  { id: 'bmx',       label: 'BMX',       icon: '⬡' },
  { id: 'indoor',    label: 'Indoor training', icon: '⬚' },
];

const EVENT_TYPES = [
  'Rail jam',
  'Park event',
  'Ski comp',
  'Snowboard comp',
  'Banked slalom',
  'Demo day',
  'Freestyle clinic',
  'Indoor session',
  'Skate jam',
  'Gear swap',
  'Film night',
];

const EVENTS = [
  {
    id: 'e1',
    title: 'Midnight Rail Riot',
    org: 'Blue Mountain Park Crew',
    orgVerified: true,
    sport: 'snowboard',
    type: 'Rail jam',
    skill: 'All levels',
    cost: 'Free',
    prize: '$2,000 cash + product',
    when: 'Sat · Nov 14 · 7:00 PM',
    deadline: 'Reg closes Fri 11pm',
    distanceKm: 38,
    indoor: false,
    saved: false,
    going: 47,
    live: true,
    featured: true,
    coords: '44.5018° N · 80.3097° W',
    location: 'Blue Mountain Resort · Park 2',
    desc: 'Annual night rail jam under the lights. Open division + groms. Cash for best trick, judged by Burton team riders. New down-flat-down setup this year.',
    sponsors: ['Burton', 'CAPiTA', 'Cardiel'],
    color: 95,
  },
  {
    id: 'e2',
    title: 'Treadmill Freestyle Block',
    org: 'Northern Slope Indoor',
    orgVerified: true,
    sport: 'indoor',
    type: 'Indoor session',
    skill: 'Intermediate',
    cost: '$45',
    prize: null,
    when: 'Tue · Nov 17 · 6:30 PM',
    deadline: 'Booking required',
    distanceKm: 12,
    indoor: true,
    saved: true,
    going: 8,
    live: false,
    coords: '43.7615° N · 79.4111° W',
    location: 'Northern Slope · Toronto',
    desc: 'Two-hour indoor block on the rotating slope. Focused on switch riding and rail prep. Coaching by ex-team riders. Limited to 12 spots.',
    sponsors: [],
    color: 280,
  },
  {
    id: 'e3',
    title: 'Banked Slalom — Qualifiers',
    org: 'Mont Tremblant',
    orgVerified: true,
    sport: 'snowboard',
    type: 'Banked slalom',
    skill: 'Open',
    cost: '$60',
    prize: 'Trip to Mt. Baker',
    when: 'Sat · Dec 5 · 9:00 AM',
    deadline: 'Reg closes Nov 28',
    distanceKm: 142,
    indoor: false,
    saved: false,
    going: 124,
    live: false,
    featured: true,
    coords: '46.2117° N · 74.5841° W',
    location: 'Mont Tremblant · North Side',
    desc: 'Two-run format on a freshly-cut banked course. Top 8 advance to the regional. Course preview Friday afternoon.',
    sponsors: ['Vans', 'Nitro'],
    color: 230,
  },
  {
    id: 'e4',
    title: 'Shop Wax & Tune Night',
    org: 'Sweet Skis',
    orgVerified: false,
    sport: 'ski',
    type: 'Demo day',
    skill: 'All',
    cost: 'Free with purchase',
    prize: null,
    when: 'Thu · Nov 19 · 5–9 PM',
    deadline: null,
    distanceKm: 4,
    indoor: false,
    saved: false,
    going: 22,
    live: false,
    coords: '43.6532° N · 79.3832° W',
    location: 'Sweet Skis · Queen W',
    desc: 'Free hot wax with any board service. Pizza, beers, and a Dakine prize draw. Bring your stick.',
    sponsors: ['Dakine'],
    color: 60,
  },
  {
    id: 'e5',
    title: 'Bowl Jam — Open Class',
    org: 'Underpass Skatepark',
    orgVerified: true,
    sport: 'skate',
    type: 'Skate jam',
    skill: 'Intermediate +',
    cost: '$10',
    prize: 'Product toss',
    when: 'Sun · Nov 22 · 2:00 PM',
    deadline: null,
    distanceKm: 7,
    indoor: false,
    saved: true,
    going: 63,
    live: false,
    coords: '43.6481° N · 79.3964° W',
    location: 'Underpass Park · Toronto',
    desc: 'Open class bowl jam, jam format, three heats. DJs all afternoon. Cash for best line, best trick, best slam.',
    sponsors: ['Adidas Skate'],
    color: 60,
  },
  {
    id: 'e6',
    title: 'Pre-Season Park Camp',
    org: 'Glide House',
    orgVerified: true,
    sport: 'indoor',
    type: 'Indoor session',
    skill: 'All levels',
    cost: '$280 / 4 days',
    prize: null,
    when: 'Nov 24 – Nov 27',
    deadline: 'Limited spots',
    distanceKm: 18,
    indoor: true,
    saved: false,
    going: 14,
    live: false,
    coords: '43.7901° N · 79.4163° W',
    location: 'Glide House · Markham',
    desc: 'Four-day pre-season camp on indoor slopes. Mornings on technique, afternoons on the airbag. Coaching by ex-Burton team riders.',
    sponsors: [],
    color: 280,
  },

  // ───── Ontario / GTA ─────
  {
    id: 'e7',
    title: 'Opening Day Throwdown',
    org: 'Blue Mountain Park Crew',
    orgVerified: true,
    sport: 'snowboard',
    type: 'Park event',
    skill: 'All levels',
    cost: 'Free with lift',
    prize: 'Demo gear giveaways',
    when: 'Sat · Dec 13 · 10:00 AM',
    deadline: null,
    distanceKm: 38,
    indoor: false,
    saved: false,
    going: 152,
    live: false,
    coords: '44.5018° N · 80.3097° W',
    location: 'Blue Mountain Resort · Park 1',
    desc: 'Annual park opening party. New jib lineup unveiled. DJ on the deck, demos from Burton, K2, and CAPiTA. Hot chocolate and toques while supplies last.',
    sponsors: ['Burton', 'K2', 'CAPiTA'],
    color: 95,
  },
  {
    id: 'e8',
    title: 'Friday Night Freestyle',
    org: 'Blue Mountain Park Crew',
    orgVerified: true,
    sport: 'snowboard',
    type: 'Freestyle clinic',
    skill: 'Intermediate',
    cost: '$60',
    prize: null,
    when: 'Fri · Dec 19 · 6:00 PM',
    deadline: 'Reg closes Thu 6pm',
    distanceKm: 38,
    indoor: false,
    saved: false,
    going: 18,
    live: false,
    coords: '44.5018° N · 80.3097° W',
    location: 'Blue Mountain Resort · Park 2',
    desc: 'Coaching clinic on rails and side-hits, two-hour block with two coaches. Bring your A-game; spots limited to 20.',
    sponsors: [],
    color: 95,
  },
  {
    id: 'e9',
    title: 'Ladies Send-It Night',
    org: 'Blue Mountain Park Crew',
    orgVerified: true,
    sport: 'snowboard',
    type: 'Park event',
    skill: 'All levels',
    cost: '$25',
    prize: 'Product toss',
    when: 'Wed · Jan 7 · 6:00 PM',
    deadline: null,
    distanceKm: 38,
    indoor: false,
    saved: false,
    going: 64,
    live: false,
    coords: '44.5018° N · 80.3097° W',
    location: 'Blue Mountain Resort · Park 1',
    desc: 'Women-only park session with coaching and giveaways. All abilities welcome. Sisters of Shred volunteer crew on hand.',
    sponsors: ['Capita', 'Vans'],
    color: 95,
  },
  {
    id: 'e10',
    title: 'Battle on the Boards',
    org: 'Blue Mountain Park Crew',
    orgVerified: true,
    sport: 'snowboard',
    type: 'Snowboard comp',
    skill: 'Open',
    cost: '$45',
    prize: '$3,000 cash purse',
    when: 'Sat · Feb 7 · 9:00 AM',
    deadline: 'Reg closes Jan 31',
    distanceKm: 38,
    indoor: false,
    saved: false,
    going: 86,
    live: false,
    coords: '44.5018° N · 80.3097° W',
    location: 'Blue Mountain Resort · Park 2',
    desc: 'Slopestyle format, three-run jam. Top 10 advance to finals. Judged by team riders from Burton and CAPiTA.',
    sponsors: ['Burton', 'CAPiTA', 'Monster'],
    color: 95,
    // Past edition results (for the Results tab demo).
    results: [
      { place: 1, rider: 'Alex Marlowe',  note: 'Three-run total · 92.4', prize: '$1,500 cash' },
      { place: 2, rider: 'Jas Singh',     note: 'Best trick · Cab 540',   prize: 'Burton kit' },
      { place: 3, rider: 'Mia Tessier',   note: 'Best rookie',            prize: 'CAPiTA board' },
    ],
  },
  {
    id: 'e11',
    title: 'Mountain Film Night',
    org: 'Blue Mountain Park Crew',
    orgVerified: true,
    sport: 'snowboard',
    type: 'Film night',
    skill: 'All',
    cost: '$15',
    prize: null,
    when: 'Thu · Jan 22 · 8:00 PM',
    deadline: null,
    distanceKm: 38,
    indoor: false,
    saved: false,
    going: 132,
    live: false,
    coords: '44.5018° N · 80.3097° W',
    location: 'Blue Mountain Village · Plaza Theatre',
    desc: 'Premiere of three new shred films. Q&A with the filmmakers, raffle for season pass upgrades.',
    sponsors: ['Mountain Dew', 'GoPro'],
    color: 95,
  },

  // ───── Toronto local ─────
  {
    id: 'e12',
    title: 'Maxxtracks New Year Bash',
    org: 'Maxxtracks',
    orgVerified: true,
    sport: 'indoor',
    type: 'Indoor session',
    skill: 'All levels',
    cost: '$55',
    prize: 'Door prizes',
    when: 'Sat · Jan 3 · 7:00 PM',
    deadline: 'Booking required',
    distanceKm: 56,
    indoor: true,
    saved: false,
    going: 22,
    live: false,
    coords: '43.3255° N · 79.7990° W',
    location: 'Maxxtracks · Burlington',
    desc: 'Two-hour rotating-slope session with coaches on hand. Pizza after. New riders welcome.',
    sponsors: [],
    color: 280,
  },
  {
    id: 'e13',
    title: 'Race Lab — Beginner Block',
    org: 'Northern Slope Indoor',
    orgVerified: true,
    sport: 'indoor',
    type: 'Indoor session',
    skill: 'Beginner',
    cost: '$45',
    prize: null,
    when: 'Tue · Dec 9 · 6:30 PM',
    deadline: 'Booking required',
    distanceKm: 12,
    indoor: true,
    saved: false,
    going: 10,
    live: false,
    coords: '43.7615° N · 79.4111° W',
    location: 'Northern Slope · Toronto',
    desc: 'Race fundamentals on the rotating slope. Stance, edging, basic gates.',
    sponsors: [],
    color: 280,
  },
  {
    id: 'e14',
    title: 'Tune & Hot Chocolate',
    org: 'Comor Sports',
    orgVerified: true,
    sport: 'ski',
    type: 'Demo day',
    skill: 'All',
    cost: 'Free',
    prize: null,
    when: 'Sat · Dec 6 · 10:00 AM',
    deadline: null,
    distanceKm: 5,
    indoor: false,
    saved: false,
    going: 38,
    live: false,
    coords: '43.6660° N · 79.3870° W',
    location: 'Comor Sports · Yonge & Eglinton',
    desc: 'Free hot wax and edge tune with any service. Free hot chocolate. Atomic and Rossignol reps on the floor.',
    sponsors: ['Atomic', 'Rossignol'],
    color: 60,
  },
  {
    id: 'e15',
    title: 'Sweet Skis Gear Swap',
    org: 'Sweet Skis',
    orgVerified: true,
    sport: 'ski',
    type: 'Gear swap',
    skill: 'All',
    cost: 'Free entry',
    prize: null,
    when: 'Sat · Nov 8 · 11:00 AM',
    deadline: null,
    distanceKm: 4,
    indoor: false,
    saved: false,
    going: 75,
    live: false,
    coords: '43.6532° N · 79.3832° W',
    location: 'Sweet Skis · Queen W',
    desc: 'Bring used gear, leave with new-to-you. Shop takes 15% commission. Coffee and pastries on the house.',
    sponsors: [],
    color: 60,
  },
  {
    id: 'e16',
    title: 'Lunchtime Bowl Sessions',
    org: 'Underpass Skatepark',
    orgVerified: true,
    sport: 'skate',
    type: 'Skate jam',
    skill: 'All',
    cost: 'Free',
    prize: null,
    when: 'Wed · Nov 19 · 12:00 PM',
    deadline: null,
    distanceKm: 7,
    indoor: false,
    saved: false,
    going: 28,
    live: false,
    coords: '43.6481° N · 79.3964° W',
    location: 'Underpass Park · Toronto',
    desc: 'Open jam session in the bowl. No comp, no judging — just shred. Ramps swept and ready by 11:30.',
    sponsors: [],
    color: 60,
  },
  {
    id: 'e17',
    title: 'Stair Set Throwdown',
    org: 'Underpass Skatepark',
    orgVerified: true,
    sport: 'skate',
    type: 'Skate jam',
    skill: 'Intermediate +',
    cost: '$15',
    prize: 'Cash for best trick',
    when: 'Sun · Apr 12 · 1:00 PM',
    deadline: null,
    distanceKm: 7,
    indoor: false,
    saved: false,
    going: 41,
    live: false,
    coords: '43.6481° N · 79.3964° W',
    location: 'Underpass Park · Toronto',
    desc: 'Best-trick comp on the new five-stair. Adidas Skate reps judging. Pizza after.',
    sponsors: ['Adidas Skate'],
    color: 60,
  },

  // ───── Quebec ─────
  {
    id: 'e18',
    title: 'Banked Slalom — Finals',
    org: 'Mont Tremblant',
    orgVerified: true,
    sport: 'snowboard',
    type: 'Banked slalom',
    skill: 'Open',
    cost: '$80',
    prize: 'Trip to Mt. Baker · sponsor product',
    when: 'Sun · Dec 6 · 10:00 AM',
    deadline: 'Qualified riders only',
    distanceKm: 142,
    indoor: false,
    saved: false,
    going: 96,
    live: false,
    coords: '46.2117° N · 74.5841° W',
    location: 'Mont Tremblant · North Side',
    desc: 'Final round of the regional banked slalom. Top 8 advance to nationals.',
    sponsors: ['Vans', 'Nitro', 'Red Bull'],
    color: 230,
  },
  {
    id: 'e19',
    title: 'Tremblant Mountain Festival',
    org: 'Mont Tremblant',
    orgVerified: true,
    sport: 'ski',
    type: 'Park event',
    skill: 'All',
    cost: 'Free with lift',
    prize: 'Daily giveaways',
    when: 'Feb 13 – Feb 15',
    deadline: null,
    distanceKm: 142,
    indoor: false,
    saved: false,
    going: 412,
    live: false,
    coords: '46.2117° N · 74.5841° W',
    location: 'Mont Tremblant Village',
    desc: 'Three-day festival: park comps, après live music, ski-and-snowboard demo expo, bonfires nightly.',
    sponsors: ['Salomon', 'K2', 'Stella Artois'],
    color: 230,
  },
  {
    id: 'e20',
    title: 'Glades & Whisky Tour',
    org: 'Le Massif',
    orgVerified: true,
    sport: 'ski',
    type: 'Demo day',
    skill: 'Intermediate',
    cost: '$140',
    prize: null,
    when: 'Sat · Jan 10 · 9:00 AM',
    deadline: 'Reg closes Jan 7',
    distanceKm: 220,
    indoor: false,
    saved: false,
    going: 18,
    live: false,
    coords: '47.2920° N · 70.5610° W',
    location: 'Le Massif · Charlevoix',
    desc: 'Guided glade-skiing with a Charlevoix distillery whisky tasting at the day-lodge after. Lift ticket included.',
    sponsors: ['Maison Sivo'],
    color: 60,
  },
  {
    id: 'e21',
    title: 'Bromont Park Open',
    org: 'Bromont',
    orgVerified: true,
    sport: 'snowboard',
    type: 'Snowboard comp',
    skill: 'Open',
    cost: '$50',
    prize: '$1,500 + product',
    when: 'Sat · Jan 24 · 10:00 AM',
    deadline: 'Reg closes Jan 17',
    distanceKm: 178,
    indoor: false,
    saved: false,
    going: 54,
    live: false,
    coords: '45.3170° N · 72.6500° W',
    location: 'Bromont · Park Nord',
    desc: 'Slopestyle qualifier for the Quebec circuit. Open division + grom division (under 14).',
    sponsors: ['Volcom', 'Nike SB'],
    color: 95,
  },

  // ───── Western Canada (Banff trio) ─────
  {
    id: 'e22',
    title: 'Sunshine Slush Cup',
    org: 'Sunshine Village',
    orgVerified: true,
    sport: 'snowboard',
    type: 'Park event',
    skill: 'All',
    cost: 'Free with lift',
    prize: 'Costume prizes',
    when: 'Sat · May 16 · 12:00 PM',
    deadline: null,
    distanceKm: 580,
    indoor: false,
    saved: false,
    going: 320,
    live: false,
    featured: true,
    coords: '51.0850° N · 115.7780° W',
    location: 'Sunshine Village · Banff',
    desc: 'Annual closing-day pond skim. Costumes mandatory. Live music, BBQ. Open to skiers and boarders.',
    sponsors: ['Salomon', 'Banff Ave Brewing'],
    color: 95,
  },
  {
    id: 'e23',
    title: 'Lake Louise Big Mountain Challenge',
    org: 'Lake Louise',
    orgVerified: true,
    sport: 'ski',
    type: 'Ski comp',
    skill: 'Pro',
    cost: '$95',
    prize: 'IFSA points · cash purse',
    when: 'Mar 14 – Mar 15',
    deadline: 'Pre-qualified only',
    distanceKm: 580,
    indoor: false,
    saved: false,
    going: 64,
    live: false,
    coords: '51.4310° N · 116.1820° W',
    location: 'Lake Louise · West Bowl',
    desc: 'IFSA-sanctioned big-mountain comp on the West Bowl venue. Two-day format with judged runs.',
    sponsors: ['Atomic', 'Smith', 'Red Bull'],
    color: 60,
  },
  {
    id: 'e24',
    title: 'Norquay Night Lights Rail Jam',
    org: 'Mt Norquay',
    orgVerified: true,
    sport: 'snowboard',
    type: 'Rail jam',
    skill: 'All',
    cost: '$25',
    prize: '$1,000 product',
    when: 'Fri · Feb 6 · 6:30 PM',
    deadline: null,
    distanceKm: 580,
    indoor: false,
    saved: false,
    going: 78,
    live: false,
    coords: '51.2090° N · 115.6020° W',
    location: 'Mt Norquay · Cascade Park',
    desc: 'Under-the-lights rail jam. New down-flat-down + S-rail this season. Coed format.',
    sponsors: ['CAPiTA', 'Monster'],
    color: 95,
  },

  // ───── Year-round / off-season ─────
  {
    id: 'e25',
    title: 'COP Skate Camp',
    org: 'Canada Olympic Park',
    orgVerified: true,
    sport: 'skate',
    type: 'Freestyle clinic',
    skill: 'All',
    cost: '$280 / 4 days',
    prize: null,
    when: 'Jul 6 – Jul 9',
    deadline: 'Reg closes Jun 28',
    distanceKm: 600,
    indoor: false,
    saved: false,
    going: 30,
    live: false,
    coords: '51.0790° N · 114.2150° W',
    location: 'Canada Olympic Park · Calgary',
    desc: 'Four-day skate camp on the Olympic-grade plaza and bowls. Ages 10–18. Pro coaches.',
    sponsors: ['Vans', 'Element'],
    color: 60,
  },
  {
    id: 'e26',
    title: 'Cumberland Bowl Jam',
    org: 'Cumberland Skatepark',
    orgVerified: true,
    sport: 'skate',
    type: 'Skate jam',
    skill: 'All',
    cost: 'Free',
    prize: 'Product toss',
    when: 'Sat · Jul 18 · 1:00 PM',
    deadline: null,
    distanceKm: 410,
    indoor: false,
    saved: false,
    going: 92,
    live: false,
    coords: '45.4220° N · 75.5860° W',
    location: 'Cumberland Park · Ottawa',
    desc: 'Annual jam on the deep concrete bowl. Best-line, best-trick, best-slam. DJ all afternoon.',
    sponsors: ['Spitfire', 'Independent'],
    color: 60,
    results: [
      { place: 1, rider: 'Devon Park',     note: 'Best line',  prize: '$500 + product' },
      { place: 2, rider: 'Kai Yamamoto',   note: 'Best trick', prize: 'Spitfire wheels' },
      { place: 3, rider: 'Riley Tremblay', note: 'Best slam',  prize: 'Indy trucks' },
    ],
  },
  {
    id: 'e27',
    title: 'Glide House Summer Camp',
    org: 'Glide House',
    orgVerified: true,
    sport: 'indoor',
    type: 'Indoor session',
    skill: 'All',
    cost: '$420 / 5 days',
    prize: null,
    when: 'Aug 10 – Aug 14',
    deadline: 'Reg closes Aug 1',
    distanceKm: 18,
    indoor: true,
    saved: false,
    going: 24,
    live: false,
    coords: '43.7901° N · 79.4163° W',
    location: 'Glide House · Markham',
    desc: 'Five-day pre-season camp. Mornings on the rotating slope, afternoons on the airbag. Ages 12+.',
    sponsors: [],
    color: 280,
  },
  {
    id: 'e28',
    title: 'Hardware Hangout',
    org: 'Sweet Skis',
    orgVerified: true,
    sport: 'snowboard',
    type: 'Demo day',
    skill: 'All',
    cost: 'Free',
    prize: null,
    when: 'Sat · Mar 14 · 11:00 AM',
    deadline: null,
    distanceKm: 4,
    indoor: false,
    saved: false,
    going: 26,
    live: false,
    coords: '43.6532° N · 79.3832° W',
    location: 'Sweet Skis · Queen W',
    desc: 'Try this season\'s board-and-binding setups in the parking lot mock park. Burton, CAPiTA, K2 reps on hand.',
    sponsors: ['Burton', 'CAPiTA', 'K2'],
    color: 95,
  },
  {
    id: 'e29',
    title: 'Spring Send-Off',
    org: 'Blue Mountain Park Crew',
    orgVerified: true,
    sport: 'snowboard',
    type: 'Park event',
    skill: 'All',
    cost: 'Free with lift',
    prize: 'Costume prizes · gear giveaway',
    when: 'Sat · Apr 4 · 11:00 AM',
    deadline: null,
    distanceKm: 38,
    indoor: false,
    saved: false,
    going: 248,
    live: false,
    coords: '44.5018° N · 80.3097° W',
    location: 'Blue Mountain · Big Park',
    desc: 'Closing-day jib jam + costume contest. Pond skim at 3pm if conditions allow. Live band on the deck.',
    sponsors: ['Burton', 'Coors'],
    color: 95,
  },
  {
    id: 'e30',
    title: 'Glide House Wine & Carve',
    org: 'Glide House',
    orgVerified: true,
    sport: 'indoor',
    type: 'Indoor session',
    skill: 'All adults',
    cost: '$95',
    prize: null,
    when: 'Fri · Feb 27 · 8:00 PM',
    deadline: 'Booking required',
    distanceKm: 18,
    indoor: true,
    saved: false,
    going: 16,
    live: false,
    coords: '43.7901° N · 79.4163° W',
    location: 'Glide House · Markham',
    desc: '21+ evening session. 60 minutes on the slope, then a guided wine tasting. Coaches on hand for the slope segment.',
    sponsors: ['Trius Winery'],
    color: 280,
  },
];

const GEAR_DEALS = [
  {
    id: 'g1', shop: 'Sweet Skis', kind: 'Local shop',
    title: 'CAPiTA Mercury 155 — 2025',
    sale: 549, original: 749, off: 27,
    sport: 'snowboard', distanceKm: 4, sponsored: false,
  },
  {
    id: 'g2', shop: 'Burton Direct', kind: 'Brand deal',
    title: 'Cartel X EST Bindings — Black',
    sale: 299, original: 399, off: 25,
    sport: 'snowboard', distanceKm: null, sponsored: true,
  },
  {
    id: 'g3', shop: 'Sport Chek', kind: 'Affiliate',
    title: 'Smith Squad MAG Goggles',
    sale: 169, original: 240, off: 30,
    sport: 'ski', distanceKm: 6, sponsored: false,
  },
  {
    id: 'g4', shop: 'Underpass Shop', kind: 'Local shop',
    title: 'Independent 144 Trucks (pair)',
    sale: 64, original: 80, off: 20,
    sport: 'skate', distanceKm: 7, sponsored: false,
  },
  {
    id: 'g5', shop: 'Dakine', kind: 'Event sponsor',
    title: 'Heli Pro 20L Pack',
    sale: 89, original: 120, off: 26,
    sport: 'ski', distanceKm: null, sponsored: true,
  },
];

const NOTIFICATIONS = [
  { id: 'n1', kind: 'new', text: 'New rail jam within 80 km',
    sub: 'Midnight Rail Riot · Blue Mountain · Sat',
    time: '2h ago', unread: true },
  { id: 'n2', kind: 'deadline', text: 'Registration closes tomorrow',
    sub: 'Banked Slalom Qualifiers · Mont Tremblant',
    time: '5h ago', unread: true },
  { id: 'n3', kind: 'indoor', text: 'Indoor session added this weekend',
    sub: 'Northern Slope · Treadmill Freestyle Block',
    time: '1d ago', unread: false },
  { id: 'n4', kind: 'gear', text: 'Gear deal matching your interests',
    sub: 'CAPiTA Mercury 155 — 27% off · Sweet Skis',
    time: '2d ago', unread: false },
  { id: 'n5', kind: 'changed', text: 'Event location updated',
    sub: 'Bowl Jam moved to lower bowl, 2pm start',
    time: '3d ago', unread: false },
];

// Seed riders for the "Riders near you" feature. Real version pulls from the
// `profiles` table; until then, these are placeholders so the UI has something
// to render. Each rider has consented (in this fictional world) to be visible
// in their region.
const RIDERS = [
  {
    id: 'r1', name: 'Alex Marlowe', initials: 'AM',
    homeMountain: 'Blue Mountain', city: 'Toronto',
    sports: ['snowboard', 'skate'], skill: 'Intermediate',
    bio: 'Park rat, weekend warrior. Looking for crew for Wednesday night sessions at Blue.',
    available: true, distanceKm: 12, color: 95,
    accolades: [{ title: '2nd Place', event: 'Underpass Bowl Jam', year: 2024 }],
  },
  {
    id: 'r2', name: 'Jas Singh', initials: 'JS',
    homeMountain: 'Mont Tremblant', city: 'Montreal',
    sports: ['snowboard'], skill: 'Open',
    bio: 'Banked slalom + park. Down to drive for big events.',
    available: true, distanceKm: 18, color: 230,
    accolades: [
      { title: '1st Place', event: 'Bromont Park Open', year: 2024 },
      { title: 'Best Trick', event: 'Battle on the Boards', year: 2025 },
    ],
  },
  {
    id: 'r3', name: 'Mia Tessier', initials: 'MT',
    homeMountain: 'Glide House', city: 'Markham',
    sports: ['snowboard', 'indoor'], skill: 'Intermediate',
    bio: 'Indoor sessions year-round. Always down to skate the dome on rainy days.',
    available: true, distanceKm: 8, color: 280,
    accolades: [{ title: 'Best Rookie', event: 'Battle on the Boards', year: 2024 }],
  },
  {
    id: 'r4', name: 'Devon Park', initials: 'DP',
    homeMountain: 'Underpass Skatepark', city: 'Toronto',
    sports: ['skate'], skill: 'Pro',
    bio: 'Bowl every day. Hit me up for early morning sessions, parks open at 8.',
    available: true, distanceKm: 5, color: 60,
    accolades: [
      { title: '1st Place', event: 'Bowl Jam — Open Class', year: 2025 },
      { title: 'Best Line', event: 'Cumberland Bowl Jam', year: 2025 },
    ],
  },
  {
    id: 'r5', name: 'Kai Yamamoto', initials: 'KY',
    homeMountain: 'Northern Slope', city: 'Toronto',
    sports: ['ski', 'indoor'], skill: 'Advanced',
    bio: 'Race-focused. Indoor 3x a week, weekend trips to Blue.',
    available: false, distanceKm: 9, color: 60,
    accolades: [{ title: '2nd Place', event: 'Lake Louise Big Mountain', year: 2024 }],
  },
  {
    id: 'r6', name: 'Riley Tremblay', initials: 'RT',
    homeMountain: 'Cumberland', city: 'Ottawa',
    sports: ['skate', 'snowboard'], skill: 'Intermediate',
    bio: 'Ottawa-based. Down for road trips. Hit me up if you need a +1 to anything.',
    available: true, distanceKm: 410, color: 95,
    accolades: [],
  },
  {
    id: 'r7', name: 'Sam Kelly', initials: 'SK',
    homeMountain: 'Sweet Skis', city: 'Toronto',
    sports: ['ski'], skill: 'Intermediate',
    bio: 'Shop kid. Saturdays at Blue, weekday lunches at the dome.',
    available: true, distanceKm: 4, color: 60,
    accolades: [],
  },
  {
    id: 'r8', name: 'Nora Strom', initials: 'NS',
    homeMountain: 'Whistler', city: 'Vancouver',
    sports: ['snowboard'], skill: 'Pro',
    bio: 'BC-based. Travel for film projects and contests. Looking for crew on East Coast trips.',
    available: true, distanceKm: 3300, color: 230,
    accolades: [
      { title: '1st Place', event: 'Whistler Slopestyle Open', year: 2024 },
      { title: 'Featured Rider', event: 'Burton Mountain Festival', year: 2025 },
    ],
  },
];

// Comprehensive US + Canada metro list. Used by:
//   - Onboarding city picker (GPS snap-to-nearest)
//   - LeafletMap CITY_COORDS lookup
//   - Ingest pipeline Eventbrite region scan
// Each entry = a metro that hosts mountain/skate/action-sport activity.
const NA_CITIES = [
  // ── Canada — provinces (capital or largest metro per province where action-sport activity exists)
  { name: 'Toronto',       region: 'ON', country: 'CA', lat: 43.6532, lon: -79.3832 },
  { name: 'Ottawa',        region: 'ON', country: 'CA', lat: 45.4215, lon: -75.6972 },
  { name: 'Sudbury',       region: 'ON', country: 'CA', lat: 46.4917, lon: -80.9930 },
  { name: 'Thunder Bay',   region: 'ON', country: 'CA', lat: 48.3809, lon: -89.2477 },
  { name: 'Montreal',      region: 'QC', country: 'CA', lat: 45.5019, lon: -73.5674 },
  { name: 'Quebec City',   region: 'QC', country: 'CA', lat: 46.8139, lon: -71.2080 },
  { name: 'Saguenay',      region: 'QC', country: 'CA', lat: 48.4280, lon: -71.0680 },
  { name: 'Halifax',       region: 'NS', country: 'CA', lat: 44.6488, lon: -63.5752 },
  { name: 'Sydney',        region: 'NS', country: 'CA', lat: 46.1351, lon: -60.1831 },
  { name: 'Fredericton',   region: 'NB', country: 'CA', lat: 45.9636, lon: -66.6431 },
  { name: 'Saint John',    region: 'NB', country: 'CA', lat: 45.2733, lon: -66.0633 },
  { name: 'Charlottetown', region: 'PE', country: 'CA', lat: 46.2382, lon: -63.1311 },
  { name: "St. John's",    region: 'NL', country: 'CA', lat: 47.5615, lon: -52.7126 },
  { name: 'Winnipeg',      region: 'MB', country: 'CA', lat: 49.8951, lon: -97.1384 },
  { name: 'Regina',        region: 'SK', country: 'CA', lat: 50.4452, lon: -104.6189 },
  { name: 'Saskatoon',     region: 'SK', country: 'CA', lat: 52.1332, lon: -106.6700 },
  { name: 'Calgary',       region: 'AB', country: 'CA', lat: 51.0447, lon: -114.0719 },
  { name: 'Edmonton',      region: 'AB', country: 'CA', lat: 53.5461, lon: -113.4938 },
  { name: 'Banff',         region: 'AB', country: 'CA', lat: 51.1784, lon: -115.5708 },
  { name: 'Canmore',       region: 'AB', country: 'CA', lat: 51.0884, lon: -115.3479 },
  { name: 'Vancouver',     region: 'BC', country: 'CA', lat: 49.2827, lon: -123.1207 },
  { name: 'Victoria',      region: 'BC', country: 'CA', lat: 48.4284, lon: -123.3656 },
  { name: 'Whistler',      region: 'BC', country: 'CA', lat: 50.1163, lon: -122.9574 },
  { name: 'Kelowna',       region: 'BC', country: 'CA', lat: 49.8880, lon: -119.4960 },
  { name: 'Whitehorse',    region: 'YT', country: 'CA', lat: 60.7212, lon: -135.0568 },
  { name: 'Yellowknife',   region: 'NT', country: 'CA', lat: 62.4540, lon: -114.3718 },
  { name: 'Iqaluit',       region: 'NU', country: 'CA', lat: 63.7467, lon: -68.5170 },

  // ── United States — top action-sport metros across all 50 states
  { name: 'Seattle',         region: 'WA', country: 'US', lat: 47.6062, lon: -122.3321 },
  { name: 'Spokane',         region: 'WA', country: 'US', lat: 47.6588, lon: -117.4260 },
  { name: 'Portland',        region: 'OR', country: 'US', lat: 45.5152, lon: -122.6784 },
  { name: 'Bend',            region: 'OR', country: 'US', lat: 44.0582, lon: -121.3153 },
  { name: 'San Francisco',   region: 'CA', country: 'US', lat: 37.7749, lon: -122.4194 },
  { name: 'Lake Tahoe',      region: 'CA', country: 'US', lat: 39.0968, lon: -120.0324 },
  { name: 'Mammoth Lakes',   region: 'CA', country: 'US', lat: 37.6485, lon: -118.9721 },
  { name: 'Los Angeles',     region: 'CA', country: 'US', lat: 34.0522, lon: -118.2437 },
  { name: 'San Diego',       region: 'CA', country: 'US', lat: 32.7157, lon: -117.1611 },
  { name: 'Reno',            region: 'NV', country: 'US', lat: 39.5296, lon: -119.8138 },
  { name: 'Las Vegas',       region: 'NV', country: 'US', lat: 36.1699, lon: -115.1398 },
  { name: 'Boise',           region: 'ID', country: 'US', lat: 43.6150, lon: -116.2023 },
  { name: 'Sun Valley',      region: 'ID', country: 'US', lat: 43.6963, lon: -114.3517 },
  { name: 'Bozeman',         region: 'MT', country: 'US', lat: 45.6794, lon: -111.0448 },
  { name: 'Whitefish',       region: 'MT', country: 'US', lat: 48.4108, lon: -114.3375 },
  { name: 'Big Sky',         region: 'MT', country: 'US', lat: 45.2841, lon: -111.4015 },
  { name: 'Jackson',         region: 'WY', country: 'US', lat: 43.4799, lon: -110.7624 },
  { name: 'Salt Lake City',  region: 'UT', country: 'US', lat: 40.7608, lon: -111.8910 },
  { name: 'Park City',       region: 'UT', country: 'US', lat: 40.6461, lon: -111.4980 },
  { name: 'Denver',          region: 'CO', country: 'US', lat: 39.7392, lon: -104.9903 },
  { name: 'Aspen',           region: 'CO', country: 'US', lat: 39.1911, lon: -106.8175 },
  { name: 'Vail',            region: 'CO', country: 'US', lat: 39.6403, lon: -106.3742 },
  { name: 'Steamboat',       region: 'CO', country: 'US', lat: 40.4850, lon: -106.8317 },
  { name: 'Telluride',       region: 'CO', country: 'US', lat: 37.9375, lon: -107.8123 },
  { name: 'Albuquerque',     region: 'NM', country: 'US', lat: 35.0844, lon: -106.6504 },
  { name: 'Taos',            region: 'NM', country: 'US', lat: 36.4072, lon: -105.5734 },
  { name: 'Phoenix',         region: 'AZ', country: 'US', lat: 33.4484, lon: -112.0740 },
  { name: 'Flagstaff',       region: 'AZ', country: 'US', lat: 35.1983, lon: -111.6513 },
  { name: 'Honolulu',        region: 'HI', country: 'US', lat: 21.3069, lon: -157.8583 },
  { name: 'Anchorage',       region: 'AK', country: 'US', lat: 61.2181, lon: -149.9003 },
  { name: 'Minneapolis',     region: 'MN', country: 'US', lat: 44.9778, lon: -93.2650 },
  { name: 'Duluth',          region: 'MN', country: 'US', lat: 46.7867, lon: -92.1005 },
  { name: 'Madison',         region: 'WI', country: 'US', lat: 43.0731, lon: -89.4012 },
  { name: 'Milwaukee',       region: 'WI', country: 'US', lat: 43.0389, lon: -87.9065 },
  { name: 'Chicago',         region: 'IL', country: 'US', lat: 41.8781, lon: -87.6298 },
  { name: 'Detroit',         region: 'MI', country: 'US', lat: 42.3314, lon: -83.0458 },
  { name: 'Grand Rapids',    region: 'MI', country: 'US', lat: 42.9634, lon: -85.6681 },
  { name: 'Indianapolis',    region: 'IN', country: 'US', lat: 39.7684, lon: -86.1581 },
  { name: 'Cleveland',       region: 'OH', country: 'US', lat: 41.4993, lon: -81.6944 },
  { name: 'Columbus',        region: 'OH', country: 'US', lat: 39.9612, lon: -82.9988 },
  { name: 'Pittsburgh',      region: 'PA', country: 'US', lat: 40.4406, lon: -79.9959 },
  { name: 'Philadelphia',    region: 'PA', country: 'US', lat: 39.9526, lon: -75.1652 },
  { name: 'Buffalo',         region: 'NY', country: 'US', lat: 42.8864, lon: -78.8784 },
  { name: 'New York',        region: 'NY', country: 'US', lat: 40.7128, lon: -74.0060 },
  { name: 'Albany',          region: 'NY', country: 'US', lat: 42.6526, lon: -73.7562 },
  { name: 'Lake Placid',     region: 'NY', country: 'US', lat: 44.2795, lon: -73.9799 },
  { name: 'Boston',          region: 'MA', country: 'US', lat: 42.3601, lon: -71.0589 },
  { name: 'Burlington',      region: 'VT', country: 'US', lat: 44.4759, lon: -73.2121 },
  { name: 'Stowe',           region: 'VT', country: 'US', lat: 44.4654, lon: -72.6874 },
  { name: 'Manchester',      region: 'NH', country: 'US', lat: 42.9956, lon: -71.4548 },
  { name: 'North Conway',    region: 'NH', country: 'US', lat: 44.0537, lon: -71.1281 },
  { name: 'Portland',        region: 'ME', country: 'US', lat: 43.6591, lon: -70.2568 },
  { name: 'Killington',      region: 'VT', country: 'US', lat: 43.6203, lon: -72.7881 },
  { name: 'Providence',      region: 'RI', country: 'US', lat: 41.8240, lon: -71.4128 },
  { name: 'Hartford',        region: 'CT', country: 'US', lat: 41.7637, lon: -72.6851 },
  { name: 'Newark',          region: 'NJ', country: 'US', lat: 40.7357, lon: -74.1724 },
  { name: 'Charlotte',       region: 'NC', country: 'US', lat: 35.2271, lon: -80.8431 },
  { name: 'Asheville',       region: 'NC', country: 'US', lat: 35.5951, lon: -82.5515 },
  { name: 'Atlanta',         region: 'GA', country: 'US', lat: 33.7490, lon: -84.3880 },
  { name: 'Nashville',       region: 'TN', country: 'US', lat: 36.1627, lon: -86.7816 },
  { name: 'Knoxville',       region: 'TN', country: 'US', lat: 35.9606, lon: -83.9207 },
  { name: 'Louisville',      region: 'KY', country: 'US', lat: 38.2527, lon: -85.7585 },
  { name: 'Charleston',      region: 'WV', country: 'US', lat: 38.3498, lon: -81.6326 },
  { name: 'Charleston',      region: 'SC', country: 'US', lat: 32.7765, lon: -79.9311 },
  { name: 'Birmingham',      region: 'AL', country: 'US', lat: 33.5186, lon: -86.8104 },
  { name: 'Jackson',         region: 'MS', country: 'US', lat: 32.2988, lon: -90.1848 },
  { name: 'Little Rock',     region: 'AR', country: 'US', lat: 34.7465, lon: -92.2896 },
  { name: 'New Orleans',     region: 'LA', country: 'US', lat: 29.9511, lon: -90.0715 },
  { name: 'Dallas',          region: 'TX', country: 'US', lat: 32.7767, lon: -96.7970 },
  { name: 'Austin',          region: 'TX', country: 'US', lat: 30.2672, lon: -97.7431 },
  { name: 'Houston',         region: 'TX', country: 'US', lat: 29.7604, lon: -95.3698 },
  { name: 'Oklahoma City',   region: 'OK', country: 'US', lat: 35.4676, lon: -97.5164 },
  { name: 'Kansas City',     region: 'MO', country: 'US', lat: 39.0997, lon: -94.5786 },
  { name: 'St. Louis',       region: 'MO', country: 'US', lat: 38.6270, lon: -90.1994 },
  { name: 'Des Moines',      region: 'IA', country: 'US', lat: 41.5868, lon: -93.6250 },
  { name: 'Omaha',           region: 'NE', country: 'US', lat: 41.2565, lon: -95.9345 },
  { name: 'Wichita',         region: 'KS', country: 'US', lat: 37.6872, lon: -97.3301 },
  { name: 'Sioux Falls',     region: 'SD', country: 'US', lat: 43.5446, lon: -96.7311 },
  { name: 'Rapid City',      region: 'SD', country: 'US', lat: 44.0805, lon: -103.2310 },
  { name: 'Fargo',           region: 'ND', country: 'US', lat: 46.8772, lon: -96.7898 },
  { name: 'Miami',           region: 'FL', country: 'US', lat: 25.7617, lon: -80.1918 },
  { name: 'Orlando',         region: 'FL', country: 'US', lat: 28.5383, lon: -81.3792 },
  { name: 'Tampa',           region: 'FL', country: 'US', lat: 27.9506, lon: -82.4572 },
  { name: 'Wilmington',      region: 'DE', country: 'US', lat: 39.7391, lon: -75.5398 },
  { name: 'Baltimore',       region: 'MD', country: 'US', lat: 39.2904, lon: -76.6122 },
  { name: 'Washington',      region: 'DC', country: 'US', lat: 38.9072, lon: -77.0369 },
  { name: 'Richmond',        region: 'VA', country: 'US', lat: 37.5407, lon: -77.4360 },
];

window.JR_DATA = { SPORTS, EVENT_TYPES, EVENTS, GEAR_DEALS, NOTIFICATIONS, RIDERS, NA_CITIES };
